### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by ganto** [ypid/yaml4rst#1]
I wrote a Gentoo [ebuild](https://github.com/ganto/linuxmonk-overlay/tree/master/dev-python/yaml4rst) for yaml4rst. However, I'm experiencing multiple issues with the default `setup.py` shipped with this project:

* Tests are installed by default. This results in an error when using the `distutils-r1` eclass:
```
Installing yaml4rst script to /var/tmp/portage/dev-python/yaml4rst-0.1.1/image/_python3.4/usr/lib/python-exec/python3.4
 * ERROR: dev-python/yaml4rst-0.1.1::linuxmonk-overlay failed (install phase):
 *   Package installs 'tests' package which is forbidden and likely a bug in the build system.
```
I could fix this error with the following patch:
```diff
diff --git a/setup.py b/setup.py
index 6cb58bb..2f2b702 100755
--- a/setup.py
+++ b/setup.py
@@ -51,7 +51,7 @@ setup(
         'Topic :: Text Processing',
     ),
     keywords='YML YAML RST reStructuresText Ansible DebOps linting docs documentation',
-    packages=find_packages(),
+    packages=find_packages(exclude=('tests',)),
     install_requires=[
         # Debian packages: python-yaml python3-yaml python-jinja2 python3-jinja2
         'PyYAML',
 ```
* However, then the DebOps template won't be installed. You can find the build output [here](http://dpaste.com/19TSFTY). With the following patch, everything seems to be installed properly:
```patch
commit 4bc0d95b94bf3894546824d16e7b1ce0c7158149
Author: Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
Date:   Wed Oct 26 10:17:27 2016 +0200

    Fix packaging

diff --git a/setup.py b/setup.py
index 6cb58bb..a842c2e 100755
--- a/setup.py
+++ b/setup.py
@@ -3,7 +3,7 @@

 import re
 import os
-from setuptools import setup, find_packages
+from setuptools import setup

 here = os.path.abspath(os.path.dirname(__file__))

@@ -51,7 +51,8 @@ setup(
         'Topic :: Text Processing',
     ),
     keywords='YML YAML RST reStructuresText Ansible DebOps linting docs documentation',
-    packages=find_packages(),
+    packages=['yaml4rst'],
+    package_data={'yaml4rst': ['templates/debops/ansible/*']},
     install_requires=[
         # Debian packages: python-yaml python3-yaml python-jinja2 python3-jinja2
         'PyYAML',
```
I don't know setuptools so well to know what exactly is misbehaving here. Just wanted to let you know my issues.

Btw. I'm using the currently Gentoo stable `dev-python/setuptools-20.6.7`.

**Comment by ypid** [comment]
Thanks very much! If all issues where like this I would have not much to do anymore :wink: I will check that tomorrow and make a new release.

**Comment by ganto** [comment]
That's the nice thing with free software. You don't always have to do everything yourself :smiley:

**Comment by ypid** [comment]
@ganto I checked the docs again and fixed the packaging based on our suggestions. Thanks again! Should be fixed in master. Can you retry before I make the release?

**Comment by ganto** [comment]
OK, great. Thanks for looking into it. It's kind of late now. I'll test it tomorrow evening.

**Comment by ganto** [comment]
I tested the new `setup.py` with Gentoo. The good news is, that the change in the `find_packages()` makes the installation error disappear (as already experienced before). 

However, the template file is still missing :disappointed: Btw. I also cannot identify it in your `pip3` output of the commit message :smirk:

**Comment by ypid** [comment]
Thanks for testing. You are right, I missed that. I was aware that `package_data` does not recurse into dirs but forgot to test it and did not notice the missing template. Should be fixed now.

**Comment by ganto** [comment]
ok, looks good now :+1:

**Comment by ypid** [comment]
All right :wink: I made a new release. Feel free to report any further issues.
